// Generated by npm run icons:generate; do not edit manually.
// Source: react-icons@5.7.0/go/GoDotFill; see ../LICENSE.react-icons.txt and ../../../LICENSE.go.txt.
import { GenIcon } from 'react-icons';

/**
 * Original GoDotFill SVG rendered through react-icons, including IconContext.
 * @param {import('react-icons').IconBaseProps} props SVG attributes, size, color and title.
 * @returns {import('react').ReactElement} The unchanged upstream icon.
 */
export function GoDotFill(props) {
  return GenIcon({
    tag: 'svg',
    attr: { viewBox: '0 0 24 24' },
    child: [
      {
        tag: 'path',
        attr: { d: 'M12 18a6 6 0 1 0 0-12 6 6 0 0 0 0 12Z' },
        child: [],
      },
    ],
  })(props);
}
