import fs from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { createRequire } from 'node:module';
import { createHash } from 'node:crypto';
import { format } from 'prettier';
import { collectGlyphs, extractGlyphs } from './source.mjs';

const root = fileURLToPath(new URL('../../', import.meta.url));
const require = createRequire(import.meta.url);
const upstreamRoot = path.dirname(require.resolve('react-icons'));
const output = path.join(root, 'packages/icons/src/glyphs');
const marker = '// Generated by npm run icons:generate; do not edit manually.';
const check = process.argv.includes('--check');

/**
 * Build a deterministic set of standalone icon modules, inventory and upstream
 * notices from current source imports. Normal builds consume the tracked files;
 * this maintenance command uses only installed dev tooling and makes no requests.
 * @returns {Promise<Map<string, string>>} Relative output filenames and contents.
 */
async function expectedFiles() {
  const icons = await collectGlyphs(root);
  const { version } = JSON.parse(
    await fs.readFile(path.join(upstreamRoot, 'package.json'), 'utf8'),
  );
  const files = new Map();
  const inventory = [];
  for (const set of [...new Set(icons.map((icon) => icon.set))]) {
    // Each extracted family keeps its upstream copyright and license notice.
    await fs.access(path.join(root, `packages/icons/LICENSE.${set}.txt`));
    const names = icons
      .filter((icon) => icon.set === set)
      .map((icon) => icon.name);
    const code = await fs.readFile(
      path.join(upstreamRoot, set, 'index.mjs'),
      'utf8',
    );
    for (const [name, declaration] of extractGlyphs(code, set, names)) {
      const source =
        `${marker}\n` +
        `// Source: react-icons@${version}/${set}/${name}; see ../LICENSE.react-icons.txt and ../../../LICENSE.${set}.txt.\n` +
        `import { GenIcon } from 'react-icons';\n\n` +
        `/**\n * Original ${name} SVG rendered through react-icons, including IconContext.\n` +
        ` * @param {import('react-icons').IconBaseProps} props SVG attributes, size, color and title.\n` +
        ` * @returns {import('react').ReactElement} The unchanged upstream icon.\n */\n${declaration}\n`;
      files.set(
        `${set}/${name}.js`,
        await format(source, { parser: 'babel', singleQuote: true }),
      );
      inventory.push({
        set,
        name,
        sourceSha256: createHash('sha256').update(declaration).digest('hex'),
      });
    }
  }
  inventory.sort((a, b) =>
    `${a.set}/${a.name}`.localeCompare(`${b.set}/${b.name}`),
  );
  // The enclosing @myapp/icons package already declares type: module.
  // A nested package.json would be interpreted as another project by Nx.
  files.set(
    'manifest.json',
    JSON.stringify(
      { source: 'react-icons', version, icons: inventory },
      null,
      2,
    ) + '\n',
  );
  files.set(
    'LICENSE.react-icons.txt',
    await fs.readFile(path.join(upstreamRoot, 'LICENSE'), 'utf8'),
  );
  return files;
}

/** List generated output only; refuse unknown files instead of deleting user work. */
async function existingFiles(directory = output, prefix = '') {
  let entries;
  try {
    entries = await fs.readdir(directory, { withFileTypes: true });
  } catch (error) {
    if (error.code === 'ENOENT') return [];
    throw error;
  }
  const files = [];
  for (const entry of entries) {
    const relative = prefix + entry.name;
    if (entry.isDirectory())
      files.push(
        ...(await existingFiles(
          path.join(directory, entry.name),
          relative + '/',
        )),
      );
    else if (entry.isFile()) files.push(relative);
    else
      throw new Error(
        `Unexpected symlink or special file in generated output: ${relative}`,
      );
  }
  return files;
}

try {
  const files = await expectedFiles();
  const existing = await existingFiles();
  const stale = [];
  for (const [name, expected] of files) {
    const filename = path.join(output, name);
    const actual = await fs.readFile(filename, 'utf8').catch((error) => {
      if (error.code === 'ENOENT') return null;
      throw error;
    });
    if (actual === expected) continue;
    if (actual !== null && name.endsWith('.js') && !actual.startsWith(marker)) {
      throw new Error(`Refusing to overwrite non-generated ${name}.`);
    }
    stale.push(name);
    if (!check) {
      await fs.mkdir(path.dirname(filename), { recursive: true });
      await fs.writeFile(filename, expected);
    }
  }
  for (const name of existing.filter((name) => !files.has(name))) {
    const filename = path.join(output, name);
    if (
      !name.endsWith('.js') ||
      !(await fs.readFile(filename, 'utf8')).startsWith(marker)
    ) {
      throw new Error(`Unexpected non-generated output: ${name}.`);
    }
    stale.push(name);
    if (!check) await fs.unlink(filename);
  }
  if (check && stale.length)
    throw new Error(
      `Icon files are stale (${stale
        .slice(0, 6)
        .join(', ')}). Run npm run icons:generate.`,
    );
  console.log(
    `${check ? 'Verified' : 'Generated'} ${[...files.keys()].filter((name) => name.endsWith('.js')).length} individual icons; ${
      stale.length
    } file(s) ${check ? 'stale' : 'updated'}.`,
  );
} catch (error) {
  console.error(error.message);
  process.exitCode = 1;
}
