// Generated by npm run icons:generate; do not edit manually.
// Source: react-icons@5.7.0/lu/LuCircleCheckBig; see ../LICENSE.react-icons.txt and ../../../LICENSE.lu.txt.
import { GenIcon } from 'react-icons';

/**
 * Original LuCircleCheckBig SVG rendered through react-icons, including IconContext.
 * @param {import('react-icons').IconBaseProps} props SVG attributes, size, color and title.
 * @returns {import('react').ReactElement} The unchanged upstream icon.
 */
export function LuCircleCheckBig(props) {
  return GenIcon({
    tag: 'svg',
    attr: {
      viewBox: '0 0 24 24',
      fill: 'none',
      stroke: 'currentColor',
      strokeWidth: '2',
      strokeLinecap: 'round',
      strokeLinejoin: 'round',
    },
    child: [
      {
        tag: 'path',
        attr: { d: 'M21.801 10A10 10 0 1 1 17 3.335' },
        child: [],
      },
      { tag: 'path', attr: { d: 'm9 11 3 3L22 4' }, child: [] },
    ],
  })(props);
}
