// Generated by npm run icons:generate; do not edit manually.
// Source: react-icons@5.7.0/lu/LuCircleAlert; see ../LICENSE.react-icons.txt and ../../../LICENSE.lu.txt.
import { GenIcon } from 'react-icons';

/**
 * Original LuCircleAlert SVG rendered through react-icons, including IconContext.
 * @param {import('react-icons').IconBaseProps} props SVG attributes, size, color and title.
 * @returns {import('react').ReactElement} The unchanged upstream icon.
 */
export function LuCircleAlert(props) {
  return GenIcon({
    tag: 'svg',
    attr: {
      viewBox: '0 0 24 24',
      fill: 'none',
      stroke: 'currentColor',
      strokeWidth: '2',
      strokeLinecap: 'round',
      strokeLinejoin: 'round',
    },
    child: [
      { tag: 'circle', attr: { cx: '12', cy: '12', r: '10' }, child: [] },
      {
        tag: 'line',
        attr: { x1: '12', x2: '12', y1: '8', y2: '12' },
        child: [],
      },
      {
        tag: 'line',
        attr: { x1: '12', x2: '12.01', y1: '16', y2: '16' },
        child: [],
      },
    ],
  })(props);
}
