// Generated by npm run icons:generate; do not edit manually.
// Source: react-icons@5.7.0/lu/LuInfo; see ../LICENSE.react-icons.txt and ../../../LICENSE.lu.txt.
import { GenIcon } from 'react-icons';

/**
 * Original LuInfo SVG rendered through react-icons, including IconContext.
 * @param {import('react-icons').IconBaseProps} props SVG attributes, size, color and title.
 * @returns {import('react').ReactElement} The unchanged upstream icon.
 */
export function LuInfo(props) {
  return GenIcon({
    tag: 'svg',
    attr: {
      viewBox: '0 0 24 24',
      fill: 'none',
      stroke: 'currentColor',
      strokeWidth: '2',
      strokeLinecap: 'round',
      strokeLinejoin: 'round',
    },
    child: [
      { tag: 'circle', attr: { cx: '12', cy: '12', r: '10' }, child: [] },
      { tag: 'path', attr: { d: 'M12 16v-4' }, child: [] },
      { tag: 'path', attr: { d: 'M12 8h.01' }, child: [] },
    ],
  })(props);
}
