// Generated by npm run icons:generate; do not edit manually.
// Source: react-icons@5.7.0/lu/LuMenu; see ../LICENSE.react-icons.txt and ../../../LICENSE.lu.txt.
import { GenIcon } from 'react-icons';

/**
 * Original LuMenu SVG rendered through react-icons, including IconContext.
 * @param {import('react-icons').IconBaseProps} props SVG attributes, size, color and title.
 * @returns {import('react').ReactElement} The unchanged upstream icon.
 */
export function LuMenu(props) {
  return GenIcon({
    tag: 'svg',
    attr: {
      viewBox: '0 0 24 24',
      fill: 'none',
      stroke: 'currentColor',
      strokeWidth: '2',
      strokeLinecap: 'round',
      strokeLinejoin: 'round',
    },
    child: [
      {
        tag: 'line',
        attr: { x1: '4', x2: '20', y1: '12', y2: '12' },
        child: [],
      },
      { tag: 'line', attr: { x1: '4', x2: '20', y1: '6', y2: '6' }, child: [] },
      {
        tag: 'line',
        attr: { x1: '4', x2: '20', y1: '18', y2: '18' },
        child: [],
      },
    ],
  })(props);
}
