// Generated by npm run icons:generate; do not edit manually.
// Source: react-icons@5.7.0/lu/LuPencil; see ../LICENSE.react-icons.txt and ../../../LICENSE.lu.txt.
import { GenIcon } from 'react-icons';

/**
 * Original LuPencil SVG rendered through react-icons, including IconContext.
 * @param {import('react-icons').IconBaseProps} props SVG attributes, size, color and title.
 * @returns {import('react').ReactElement} The unchanged upstream icon.
 */
export function LuPencil(props) {
  return GenIcon({
    tag: 'svg',
    attr: {
      viewBox: '0 0 24 24',
      fill: 'none',
      stroke: 'currentColor',
      strokeWidth: '2',
      strokeLinecap: 'round',
      strokeLinejoin: 'round',
    },
    child: [
      {
        tag: 'path',
        attr: {
          d: 'M21.174 6.812a1 1 0 0 0-3.986-3.987L3.842 16.174a2 2 0 0 0-.5.83l-1.321 4.352a.5.5 0 0 0 .623.622l4.353-1.32a2 2 0 0 0 .83-.497z',
        },
        child: [],
      },
      { tag: 'path', attr: { d: 'm15 5 4 4' }, child: [] },
    ],
  })(props);
}
