// Generated by npm run icons:generate; do not edit manually.
// Source: react-icons@5.7.0/lu/LuSearch; see ../LICENSE.react-icons.txt and ../../../LICENSE.lu.txt.
import { GenIcon } from 'react-icons';

/**
 * Original LuSearch SVG rendered through react-icons, including IconContext.
 * @param {import('react-icons').IconBaseProps} props SVG attributes, size, color and title.
 * @returns {import('react').ReactElement} The unchanged upstream icon.
 */
export function LuSearch(props) {
  return GenIcon({
    tag: 'svg',
    attr: {
      viewBox: '0 0 24 24',
      fill: 'none',
      stroke: 'currentColor',
      strokeWidth: '2',
      strokeLinecap: 'round',
      strokeLinejoin: 'round',
    },
    child: [
      { tag: 'circle', attr: { cx: '11', cy: '11', r: '8' }, child: [] },
      { tag: 'path', attr: { d: 'm21 21-4.3-4.3' }, child: [] },
    ],
  })(props);
}
