// Generated by npm run icons:generate; do not edit manually.
// Source: react-icons@5.7.0/lu/LuTrash2; see ../LICENSE.react-icons.txt and ../../../LICENSE.lu.txt.
import { GenIcon } from 'react-icons';

/**
 * Original LuTrash2 SVG rendered through react-icons, including IconContext.
 * @param {import('react-icons').IconBaseProps} props SVG attributes, size, color and title.
 * @returns {import('react').ReactElement} The unchanged upstream icon.
 */
export function LuTrash2(props) {
  return GenIcon({
    tag: 'svg',
    attr: {
      viewBox: '0 0 24 24',
      fill: 'none',
      stroke: 'currentColor',
      strokeWidth: '2',
      strokeLinecap: 'round',
      strokeLinejoin: 'round',
    },
    child: [
      { tag: 'path', attr: { d: 'M3 6h18' }, child: [] },
      {
        tag: 'path',
        attr: { d: 'M19 6v14c0 1-1 2-2 2H7c-1 0-2-1-2-2V6' },
        child: [],
      },
      {
        tag: 'path',
        attr: { d: 'M8 6V4c0-1 1-2 2-2h4c1 0 2 1 2 2v2' },
        child: [],
      },
      {
        tag: 'line',
        attr: { x1: '10', x2: '10', y1: '11', y2: '17' },
        child: [],
      },
      {
        tag: 'line',
        attr: { x1: '14', x2: '14', y1: '11', y2: '17' },
        child: [],
      },
    ],
  })(props);
}
